---
title: "rapport"
author: "Thierry"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)
library(readxl)


```



```{r}

data <- read.csv("../data/Ambatomainty/Exported_Baseline_Ambatomainty.txt", sep = ";", strip.white = TRUE, na.strings = c("", NA)) %>% 
  mutate(DATE = dmy(DATE))

valueset <- read_excel("../data/disctionary_suivi.xlsx", 4)

# remplacer les valeurs de la colonne choix par celles de correspondance dans data
valueset_list <- valueset %>% select(choix, correpondance) %>% 
  split(valueset$variable)

# field_partners <- valueset_list[[1]][,c(3,4)] 
# names(field_partners) <- c("values", unique(valueset_list[[1]][1]))

# data_1 <- field_partners %>% 
#   right_join(data)
  

# data_2 <- data_1 %>% 
#   mutate(FIELD_PARTNER_SINGLE_FCT = values) %>% 
#   select(-values)


# Changer le nom de toutes les colonnes
data_tidy_1 <- valueset_list %>% 
  imap(function(x,y) x %>% rename_with(~paste(y), 1))

# data_tidy_2 <- valueset_list %>% 
#   imap(function(x,y) x %>% rename_with(~paste(y), 2))


# Début de réponse
data_merged <- data_tidy_1 %>% 
  map(left_join, data, by = character())

# data_merged2 <- data_tidy_1 %>% 
#   lapply(merge, data)
# 
# data_merged3 <-  data %>% 
#   reduce(data_tidy_1, left_join)

# type de données

data_roster <- data %>% 
  select(NUMERO_QUESTIONNAIRE, Q1_SOURCE_ECLAIRAGE_SINGLE_FCT_1:Q1_NOMBRE_JOURS_UTILISATION_PAR_NUM_5) %>% 
  pivot_longer(-NUMERO_QUESTIONNAIRE, 
               names_to =c(".value", "set"),
               names_pattern = "(.+)_(.)",
               values_drop_na = TRUE) 

# traitement QCM

data_qcm <- data %>%
  select(NUMERO_QUESTIONNAIRE, ends_with("_MULT_FCT"))

# data_qcm <- data %>% 
#   select(NUMERO_QUESTIONNAIRE, ends_with("_MULT_FCT")) %>% 
#   transform(Q3_ENERGIE_DE_CUISSON_MULT_FCT = strsplit(Q3_ENERGIE_DE_CUISSON_MULT_FCT, ""),
#         Q11_TYPE_D_ACTIVITE_MULT_FCT = strsplit(Q11_TYPE_D_ACTIVITE_MULT_FCT, ""),
#         Q13_PROBLEME_DE_SANTE_MULT_FCT = strsplit(Q13_PROBLEME_DE_SANTE_MULT_FCT, ""),
#         Q17_PARTICIPATION_FEMMES_ASSOC_MULT_FCT = strsplit(Q17_PARTICIPATION_FEMMES_ASSOC_MULT_FCT, "")) %>% 
#   unnest(Q3_ENERGIE_DE_CUISSON_MULT_FCT, Q11_TYPE_D_ACTIVITE_MULT_FCT) %>%  
#   unnest(Q13_PROBLEME_DE_SANTE_MULT_FCT) %>% 
#   unnest(Q17_PARTICIPATION_FEMMES_ASSOC_MULT_FCT)


data_qcmq3 <- data %>%
  select(NUMERO_QUESTIONNAIRE, Q3_ENERGIE_DE_CUISSON_MULT_FCT) %>% 
  mutate(Q3_ENERGIE_DE_CUISSON_MULT_FCT = strsplit(Q3_ENERGIE_DE_CUISSON_MULT_FCT, "")) %>%
  unnest(Q3_ENERGIE_DE_CUISSON_MULT_FCT)



```


## 

```{r}



```





## Variables sociodémographiques

```{r}

# sexe des enquêtés

sexe <- data %>% 
  select(NUMERO_QUESTIONNAIRE, SEXE_SINGLE_FCT) %>%
  mutate(SEXE_SINGLE_FCT = as.character(SEXE_SINGLE_FCT)) %>% 
  left_join(data_tidy_1$SEXE_SINGLE_FCT) %>% 
  mutate(SEXE_SINGLE_FCT = correpondance) %>% 
  select(-correpondance)

theme_set(theme_light())

sexe %>% 
  ggplot(aes(x = SEXE_SINGLE_FCT)) +
  geom_bar(aes(y = ..count../sum(..count..)), fill = "lightblue") +
  scale_y_continuous(labels=scales::percent) +
  geom_text(aes( label = scales::percent(..count../sum(..count..)),
                   y= ..count../sum(..count..) ), stat= "count", hjust = -.05) +
  ggtitle("Sexe des enquêtés") +
  coord_flip() +
  labs(
    x = NULL,
    y = "Nombre"
  )

# age des enquêtés

age <- data %>% 
  select(AGE_NUM)

age %>% 
  summarise(moyenne = mean(AGE_NUM),
            minimum = min(AGE_NUM),
            maximum = max(AGE_NUM)) 

# répartition des enqêtés par hameau
table(data$NOM_DU_HAMEAU_CHR) 

data %>% 
  select(NOM_DU_HAMEAU_CHR) %>% 
  group_by(NOM_DU_HAMEAU_CHR) %>% 
  count %>% 
  arrange(desc(n))


```



